---
# macOS specific variables

homebrew_prefix: "{{ '/opt/homebrew' if ansible_facts['architecture'] == 'arm64' else '/usr/local' }}"
homebrew_bin: "{{ homebrew_prefix }}/bin"

# Keyboard settings
macos_key_repeat: 1.0
macos_initial_key_repeat: 10.0
macos_disable_desktop_icons: true
