galaxy_info:
  role_name: configs
  description: configs setup
  author: Lvov Valery
  license: MIT
  min_ansible_version: 2.20.1
  platforms:
    - name: MacOSX
      versions:
        - all
    - name: Ubuntu
      versions:
        - all
    - name: Fedora
      versions:
        - all
